name = "avltree"
version = "0.1.0"
defaultTargets = ["avltree"]
lintDriver = "batteries/runLinter"

[[lean_lib]]
name = "avltree"


[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "main"
