name = "avlean"
version = "0.1.0"
defaultTargets = ["avlean"]
lintDriver = "batteries/runLinter"

[[lean_lib]]
name = "avlean"

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "main"
